sudo: required
services:
- docker
language: java

jdk:
  - openjdk8


env:
  global:
    - secure: i0Qex/bbEz8ElnKdeDI6TRDUTCcnufKd3CSqYwtloKbtoO0Sp0kHVlpCyYIu/fP+YjARf0scDvpFyXCxxLAgkTYFkBL+350clKZGPxRWAIWQhQaBXb7PGQX3oFGmco8k8+0WhZYvGjmpz9ReXi+7LVrMterMxLRZPws3FqsK3JajB0V/dxBJvhmYNKSocLYkXJtsx9q78CMm0byBWVXABzVpsTpcDkpM9S6fAniCDytKFhNL6O69CkkhKOyYd226EAM4qUkteXDEsLrAq0Sf8y5phHL1eUGGlHtMcCBnNC8KGgRu5FwSYFJlSoxmE5Cp0oD6LUMhqbXizX85J9tRLvYmdO5ruhxGifp6+76QtyvDClJzQU94o7AWy/52gGi9YOidPszQZWW+uisbONWi6SI36Xw7N5bh7MUxkqEv7+HgBzHiiXG7PmVwPNNdNWIf251rQArXhLDhqz81xQhkGOZiGHIht2NZAQTdFIaoKaWNBc+Tzl8D3nXQl1dMyFxCir1iq0D8C4Z/Bkek44OKC+h4qhLdCjQFAxdCpsKOgo18UjwffQaYZocXjBunelRhK8wM1vH58nu1V29ZbfxE/BOjeWeBA9upo4UgjCieUlRAnurtSenyhT6KGuTmuHOu/yJyZdSFqZtQbF1NKTscHX26mTIWMUmt/stzm4hAshA=
    - secure: AMuqqprJYCwj6e3pq+6XUaVI44bNJjWOtbiIC/2JiwdwOerRWaJbWsducsIlEVvpij0d5GvDCU/2AoPzRemiZt43BsgRZeNUK2ivXaCuLjq89y5oBLv78XWPRyOyQT9RaU/SieDX3CpUtYtnsFJLIt+CvpxQLBINq1dcyQCY1nLUys5r2Qt6nVKTZMRL9+9VDl9OB1OTvdsBvN7X/7MFeL1ljHUn+LyuzB3Nj7j2+x2BmN3fLshQhqmDoAWh2s/6K/SO/hTLNPcd4AZQCTlkvCwl5BgcEgjieNqKuN//F2NubKSkNTzU5RFjKIZ1D0PflEmP1izgZCYGYMCmLTwYGQfw//5QPXCFCO0a2EEkOg4XCMFf7XF+8qkyrXcARljG59vwPMrogpBcq5olXHlPtX+JQCYdfEFuWHFp3YIKW8J5S0XffyjnUrdIYBflX8XhNMjZd0BCN7lTtlZ4a5EiclNOBHRnNjEZVCQ0d8Mr1pF316jhKVgG5deQ656/oHFv3+3IKSult7/CsupBjf7PLlILq4/Pc8iY0ecPVRipsjRXixPq0smqeiI9SI22G8geHQlixtD+veEXxYoHNX+xV+T5Gx6NV8cPM9v/uREC05aj0Wh+7aNQ/4mFdTcTC9g0abk4zX6ddwEoHGdB4sOb2yjRO43w2e5IDNzDazESKlo=
    - secure: SZB23/2v1+kQ5R+HfMlUcbpevy9167WRV1+Wjr6M8hjjb3xFZOGZcdUs1iBR4yR7+mSlVVgpXm5CT3muAJFw25q1juLBDfEsoaERO+2lRynByylrEfD0CeowuVI5yHRDEghMK0QzxYobvXA9ORk0yK0tI7+nkZ8Uz4zYbTIM6OQWL+JLvH0reePsopEG/9ezNqrfZkzF3lzJ8hVX3FPkoxNlumZ3t5lkCn3FrkdNOZKUNRZsVh5O7zpWVatwX4bdxmvsEcZOhjqtX30PA2VsI/uL3YdPM2qd5P9cyVbKvLvXrNDzukiXnqRJn+MVXfmyy9X6sSoT80EnN1NFl2KfpylebAJDOvu3xnudfqFAanVlAw1eZibjo2nF3JiTwGYY/AiLggZdQsx4cdXm5fCLu4HtF2MIOge1eIs+SnYHUJSsMjA/yODWG+ZH0o0xW4vS/fDabHa0j3W5KdMaIF/8r0SWaI0lPldua/+dxSkFPtpz0q3Upgm9c0/1GaOagngs9sgwlJZcmHXI+yPHeNhwBrVpmP92ozr0EDj+JLl5MOT0EptOHp2k7q6dX9+RHjFIOW+mmtck8OSuzjQBtlqgWdziyUaWR/ACTVgTJS4R+DIgdBnvfh2N+IWRLQdLAshuqrTKfTmX+88rXwszGKTqUA/dwCCvCgSyJo+eXb1NZYE=

script: ./build.sh
  

after_script: ./clean.sh
