sudo: required
services:
- docker
matrix:
- language: java
- language: node_js
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.m2
before_script:
- npm install apidoc -g
script: "./build.sh"
after_script: "./clean.sh"
secure: "ePhVj2ItVSRk71uQcNilIEM8ADHpzIJroHnjtO4BllU2Qgwx+mBFqpHTkC8TM/8slZzVnBRc9MQB6v3SKw++5G1TrKae6Ncl3E+6ObcRB7tcKVfd4GeXffvhsdgWbdd6jGEGfPN6uSwwQAKzMrmPu7EvmkS+jVQgQ4PTNpUNvCzTiOu229JC2x2lv0aA6T2iGOLFHiKVCC9AFm0Af6OnBjw+OoBu1t/NtJTzLDJDcrE4V1NrPgVE6novY6ADxlA0NZID/r8DXNUqYfbiTgXEroYO6rkbbEzmlnKMRqjv2lTqLl0Qh59AzaL6ZUrcmUwrrDK0vFalTUP1+r1GH37BL6uo+RwnQUx2KW1Ah2T2SAeP3A/Y3rhItY1AzTuma0dSTWt+9aVLZ9uxA+DlLrfRF+kf4XqPQLGUKF6my1hPJndqWJflOdbaBYI4+B+DD5fotdQKfd1oRu82jb0ahGK1apULM+wib78POpdorrK4UMuKizfgd1fvVf9+RDnVd5eKfVGwXOmeafm+oLXKJRmZaObUTSq0CBUc9o9Mhy71aehJ0Im/DXcigRoevGXl8iVwvilt2ZUVJ9jS2UWm7YHaxxdQi8FWKiSY5t/8IkCiNV60RDKokifhohdgX+FtTzpMQbyy0ELqThqoE44iBd1sCwpTGXW0myRMW05xePe7S/A="
secure: "h7h888k0gT/oaotRYiRL6AkO/8TAm+3WI7LEgImZHvXN/vY71VH7ELTMSBQ8Ihvu5LhIvrGeI8cewjKl/1i8TmyXcsF3lZEBLlZQvrksMwLWhWpYjusYrOdsGAdUrsexKBSkMllXGWy+8F/gOcRUUaXN26kXJ1117dyWmwKVzb4NoBzRUfmcYBI/17uD8lFobst98o/cux42tMk7X9xeXAuErILjyfQn7A3WnyeCxX+hyvkyvtQHeklq5WtBG425eyPs8w+SFaQte5t0+wlQCzI/GznmP0AI+SQW6oxFvVmWi8s2gOKhkBrZJVPw3a0UVhNBQ+gABVMCinFh6wMNEKcmr+i77qR89MRKtIszDB/OI1Ahb0K5w3GnBdC93TPZ0lRo07wCVZTzM0OXNvsD1X4WOSvIyHKkcYb/XrgZGbWrhLAbfJ14YaNfEq345bTAi0pozvtU+qG16fUtk4i5cDF+ylew8wsNhHV3PhImjWpfNkDkD7oWaR5BjawxYdAS0eYieKcTK3pjiTR+1xQmctR/16g9fhGwPwgnL+CRCCyptg7EI2QOUvyxSkOeAy/XPRIt3CQ22feE3jmM9qYrD3fwu0TpmFYPBC9JbwvY03KkieoU+fT3BC5YWNO8q3UxrXcZQWKSQBc178iUcyIOLdU5vnnHGgYSMsbZ+Xw2D0k="
