sudo: required
services:
- docker
matrix:
- language: java
- language: node_js
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.m2
before_script:
- npm install apidoc -g
- echo $DOCKER_PASSWORD
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script: "./build.sh"
after_script: "./clean.sh"
env:
  global:
  - secure: "s/i9Cbkai+f8cgGaK9rPQBPB5gCPM3hR8Ja00Rd4uetNbvnoJanoFsZ2WVjPm1M7sF8hn69nn6VrknuQiPpr5lS5UVgfNqaYua3ID8QYW8ueRBHmhR5QgViAjuUUlq+8pV1uduXZo2LlfdrwfRN7ICV5ILYaMD9LI0G2yDErOOsKkoGwX4zxvLQjt7TumXRX6FzL3WdXvTsGCS5ZR+cyL6RclP5ESIxP7kdBaw880iSovh3qR63QpQXvWY0o8gI0kqEzF4VvAMqpNt2OfQNBaIt2VSiGPAG1A+WhGmczwqbuQbaHQKZLF5AKWhHKL0YKB+NG4Pbobq668dJlY9a0LZ8cMlh1pJQQ4T0rf1TX8XNnNJYIp0zsWxiS+TbkBziIKLGGygUltJplgGLL0fsc1wBF1oS6SbwaN6fvH7hcC7xBfcsc43CZpFvfIx9wdQ77RnDEBipZ1roDKLPpSD60jOPek1s4kGCB2mtd3yxy2AuDlVSx1x27LKbTY+qvWGNRDQUSCKt87rM070eNrxK8Di5ac3ycANVO1iWn1R1PO9bbm5LGOxRqzlzUbC+bjc+M4P1bGnsE1rroUuj4EI1jmnoYZHedsUWnsW294AjcH5z2Fx3vOezB0En/qmTlMx5m9Sad1Uq2m/SIEYFIcWV+Qc2xhBLe7U8FkXziCn927vY="
  - secure: "j3pCX36WUcbA+s5YwMPnVUgtqcaTg7hwJ5+c4saHMGPOYmNyRZ4TUm4Tzuhp04JIEkMYbvTqm6BiqJ7WCQVfmKxvIjBPudDc3eutLBsrxvJFTAhF/94tRH3XxJrTRhV7EAR22aPXelJZ4N2Ow5Vu9YsGiDB4BxMMEl84ymjyNOyfQTJh+cvolnh05MKLdlsv9Z6/TXUFRcBqfD3p1FraYm66Xr85YFufVbiBU1isQ5gJXROfnbjOu2qjcaOaC837+Ki5tp47T1Kl16IVP72aI5ScUTrAuqd0400ictWU1BCUQQNFlANyti4J07bVwVNwqtoUR0nBobSlvG893Tr7SbkXm8zTbW7J3UEY0chTdH8kFBeQSoYyMIKhkzo06VciZpw8Epl8sZQURxM4YYiUHl12OT4nZHpVA9E2F5hnuAs9jL8xUpHzsYP30Y2+LuG4JhDxSgcBNAYHfMdVU0C6GqxLJeogmq7pHRbAkzc2qFQzXGOApPXgU22+AwbOroowgrIgUSppFhNAJjsqLA7Ur85tk3BB68Lg/Z6y8bboAjyFwYHrHGw8PaKd9WeAujAZDOV2qWiG07LrwwsAtl3k0qkCG4NYjggXXaXgDiyTRIYDg2yfc6oobQh8lh9akWU+4V3F3knKZ4bq6VQiTVuCYsnVCIHS7ggAABmQ+o0YxFk="