sudo: required
services:
- docker
matrix:
- language: java
- language: node_js
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.m2
before_script:
- npm install apidoc -g
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script: "./build.sh"
after_script: "./clean.sh"
env:
  global:
  - secure: "US3/8/IW4rngnyzb8HtJVcdabqeAFUOM8i3F2geeBrhF+Ey0Gs5fapCTtwSSEE5wzkFJMgPshYUYJmRIn1l+j0rCpaA4JgVqbbteNb3A6F35NhHaq+2gWMXPewFmA+MbvE3YnF/9fPjJsM/S+DoUibSmVYRJID0RKQgNpSq2JRdWipxEx0sxF/E4IsZA2KhYwp0fqpJQoI9YZlQB1jduRMm/wNve9HU8xt+Rvy4dhkwMsOaziD3fiZtiXFJPwNrdAlVG8iVFQg6qYtR81j7uExBDqn9JTeucDd8ARCGXgWS7ReTlkLGy6Ug0yvfXNyGJ3IHA4QT/zhQFWVCo6GBdD3keEN9jOA71h22jo3NmL/sta2Y9xD/PIrQCyFsvHCNPdzXS3g5peWaBTfDlrWUIU5Vjo3hUR1XEPFzrJWkGgxclRWxJiSc3a4S05J3YkhLJAMVEVuDPA8p9iD05ikpyMC3c0XcfJwAk/6WfhhiNz+7KKqKl2Het6iafe68n7qD+YAump6rAjmKNiBNMQn+arnB6UpbhL2MQNYLxURyGB/RzdSS+tzcujv1Df/mPFkmWtjuVbDdkpxEx97Ue004fslkilHV+UPEpnyTYbJAuzQS2W2Ktc9TsiXmWxnJubbDFvJ5xkS9c+neGkDO+WatgQcSI24PPpkehYGosaBuq5/E="
  - secure: "YpUU597lY5AclGICUOA0G2oU+QNuki2MJ+d7lzjzaUuxryMk3p3yX1ug5+iJUH11uwbbiPajj3nYhG6KtOZESfrSfOmYGMKjWzc5zGFYk2R3F541JKe1+Ma3LG2iPKFdo1St0hoJzhCJyilYebWSdo54lYb/ZfTykukwEuGvMLRlATr2ek5HaptMWlmBJRamVZ8eL07tt3lQsy58PTIEgTcpTZXHIBvnveHksBvWvTElXRCnndWmwypKh4x1Nsxp2CXi2mKW98IZZsrSw0qTrq8pfpLtqdV3SM9QVkXkjbgWPjYP9UcRP6cH6yI5yJfYUCIwrzxozbN3gEWh4drr10/4rqirgsiFQMVYvnYHk24WIXgNsZpbp0iWYtc3Wh7eTvZ4Rjfmi2ZybVnvn0Tkyb4jx679txhPc2VHiC5LYn2FCbTDCLB0wIKpcZnxt1QhRd+8vF08CQUA+leEWA6NfwEFYK6fxq4HWzccOrCBKAEhmcdvE3fbjitFG0Bh85yaOV3uaO7IzI2Y5N2MHDPMh0ccgDAZsa9ccldoSCt3VlKESv7Kj7lh/+jrg0RNXIOl/kIaraqW34+6Zgdc/HDhIGADrRamQRSWEH+HfuBRfBEkLYV4jOh70D7jkCWpMntVv7S0y1ZeBODxPyT0K1PFyydvkB/n8pp4QbTGpTbWSJc="