sudo: required
services:
- docker
matrix:
- language: java
- language: node_js
jdk:
- openjdk8
before_script:
- npm install apidoc -g
script: "./build.sh"
after_success:
- docker login  -u $DOCKER_USER -p $DOCKER_PASS
- docker push aedwa038/login_db:latest
- docker push aedwa038/playground-docs:latest
after_script: "./clean.sh"
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
env:
  matrix:
  - secure: GlYMg+O3I+0EMpo8szeB5UGxr+tnpWibhdt+5g+22mz4WMHpkTy7dY9kBpcIHQVL9KfWygVq80Sj4thWhzVvjMRAQoDf8D82BgOllnsoyqmSfZP7Gki0DqQk+VYF6yOuEsov7SWCK2jdFlh/4E5Cr38aV5ghFAFFjqMdi/f4KRSNvMOwv70Z4BygD34d1SwAqjgxII7qBH54Gf58tDP6NxdZcTS1oKAvnCH9FiWRLOJbxX6KmpQXdSR8t+93qYJTQF3uMhWFXeOGRtUqO8aSpSBNjmQwzDxSbBn3MTk+hy4odX8+1qoejWB/H2/BwKjo9Ke0ZQHR4lGw5HQil118v5xpk5mT3Aq4bFAsWUfLHi7fN7AxtKXhskvPVm/H0fb0E4l9nAmgOQaIv/2yF/ZLoiwTtPcqO7848vey+2H028Rqlm3N74/jgw4ZmZcw7J5afNS220VVant8vvaUqFuzZfazIBcmy+MI6/ST79bcJliuQP0Mm0wHhjA/prcdkBFLjdnlurvpdSSYyoSwK30PMkEuQDtH8zPkv+pHxOReeCvfmUAxhWVuBXc5i+DLAsigtDB2d5Z7AEJPwKyBcPLPAS1RZaIpurVjkWNEYWGlAm23SFeaFHy+J5/utaKIIxsPRIrs5uPadYij8BJ6uYxc6AsQJuKiHwBzJ64lmSc7CZc=
  - secure: ulQZ+FIMwEkx6yZ81fh2Iv6ABsRHbLIuA0asB0tTO/EmWLT6YoMg2eAXk08c4eGtdZXozaO/ZQJVedbXH5p2rRhSeMJCBtrmZrK8T90YORsWBOKkme0GpX5PTcCnC/xjtDgNjAOK5YcsjBQXJhuG4pnOsFF4z74QnXnNunlY2e09JHgB1EigsJJrwL8EpWTTiJ20P4+O9wxaczheLS27i/rkrkb001V9xdv7PgCK5PNnbtbtRKDu1uWNVN3dCx1MRAS6vd7/TFzqDgzt1uwnM48kcWcJDCYTINNWAeHcN+55EInMsBXjNBlkARyQtGi5bhVA67jB1JJXQLI1nN1J8VTvX8iiU9YGfZSfq3NvmBkPjeCi6KlRlKVuuuX6t20Y907PhvixwDsg8f1suSTgd8KJoLO/nBTUMAd/dE7mdnBYrSv+HzawcfL3dhPnSIHWxi/ltfGsJerHA0M2SJ4UE2zDflhbGXAHHmI0sXNBvtmYcXOPOR3dqiYLFSQLWHXiOa8YNaXAPx8VpYHGgI24WjalH3wX9X9L80zDzXjZTgUwEZ/YEwJElsoT37cRYowHK9lMnziQr9xhsn7rvUQm7jInpbsWg1/Prq9OYnWLpe9b8icwQvgxkkUVELCYjfji+1rfY8z9Z4JDd2THeA14G3p2Gqq1KH+a6rvHh0M6SQY=
