#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
docker push aedwa038/playground-docs:latest
docker push aedwa038/login_db:latest
docker push aedwa038/login-playground:latest