version: "3"
services:
  database:
    build: 
       context: ./login-playground-database
       dockerfile: Dockerfile
    image: login_db
    restart: always
    ports:
      - "5432:5432" 
  login-playground-app:
    image: aedwa038/login-playground
    restart: always
    ports:
      - "9080:8080"
    depends_on:
      - database
    environment:
      #DB_HOST: jdbc:postgresql://database
      DB_USER: login
      DB_PASS: world123
      #DB_NAME: login-db  
      #DB_PORT: 5432
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://database:5432/login-db'

