#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push $DOCKER_USERNAME/playground-docs:latest
docker push $DOCKER_USERNAME/login_db:latest
docker push $DOCKER_USERNAME/login-playground:latest
